name: slide_container
description: A container that can be slid vertically and horizontally with a smooth dampened motion. Offers a handful of callbacks for customization.
version: 1.1.0
author: Quentin Le Guennec <quentin@tengio.com>
homepage: https://github.com/quentinleguennec/flutter-slide-container

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

